apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: csharpuserrp-keyvault-cert
  namespace: {{ include "server.fullname" . }}
  annotations:
    secrets-store.csi.k8s.io/enable-secret-rotation: "true"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.akvSecretsProviderClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    objects: |
      array:
        - |
          objectName: {{ .Values.certName }}
          objectType: secret
          objectVersion: "" # optional
    tenantId: {{ .Values.tenantId }} 
  secretObjects:
  - secretName: ingress-tls-secret
    type: kubernetes.io/tls
    data:
    - objectName: {{ .Values.certName }}
      key: tls.key
    - objectName: {{ .Values.certName }}
      key: tls.crt