###################################
# User inputs.
###################################
serviceInput:
  # The template name to use for this service.
  # Only used by internal templating code to determine which template to use.
  templateName: basicGoTemplate
  ################################
  # Variables required by both internal templating code and the templates.
  # The directory name after destination_dir_prefix. It holds the service.
  directoryName: basicservice
  # Whether to add this service to the umbrella pipeline
  runPipeline: true
  ################################
  # Variables required only by the service's templates.
  requiredInputs:
    # The service name in the protobuf.
    serviceName: BasicService
    # The primary email address for the service. This is for Ev2 notifications.
    contactEmail: mheberling@microsoft.com
