###################################
# User inputs.
###################################
serviceInput:
  # The template name to use for this service.
  # Only used by internal templating code to determine which template to use.
  templateName: slnmDeploymentTemplate
  ################################
  # Variables required by both internal templating code and the templates.
  # The directory name after destination_dir_prefix. It holds the service.
  directoryName: slnm-deployment
  # Whether to add this service to the umbrella pipeline
  runPipeline: false
  ################################
  # Variables required only by the service's templates.
  requiredInputs:
    # SLNM test environment configuration
    test:
      # An MSI that is a member of an AAD security group. The security group was specified when creating the ruleset in the SLNM portal.
      pipelineIdentityId: /subscriptions/359833f5-8592-40b6-8175-edc664e2196a/resourceGroups/servicehubRg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/servicehubval_mi
      # The following values are from the S360 action item:
      # --------------------------------------------------
      # Subscription that the Network Manager is deployed in (owned by SLNM team)
      subscription: 7ea7f0a6-7ba1-4165-ae53-33d63d627f94
      # Configuration ID of ruleset that was created for SLNM.
      configId: /subscriptions/7ea7f0a6-7ba1-4165-ae53-33d63d627f94/resourceGroups/dfe3a810-861c-44da-9b00-71e57a865194.rg/providers/Microsoft.Network/networkManagers/slnm.dfe3a810-861c-44da-9b00-71e57a865194.pb.corp.npd/securityAdminConfigurations/20250513.3bf009dd-48fd-4996-9b50-92157099972f
      # Resource group that the Network Manager is deployed in (owned by SLNM team)
      resourceGroup: dfe3a810-861c-44da-9b00-71e57a865194.rg
      # Name of the Network Manager that was created for SLNM.
      name: slnm.dfe3a810-861c-44da-9b00-71e57a865194.pb.corp.npd

    # SLNM prod environment configuration
    prod:
      # An MSI that is a member of a cloud group. The cloud group was specified when creating the ruleset in the SLNM portal.
      pipelineIdentityId: /subscriptions/84863f4a-6dec-4d3b-a75a-d52ac4e748b6/resourceGroups/dfe3a810-861c-44da-9b00-71e57a865194.rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/slnm-sh-mi
      # The following values are from the S360 action item
      # --------------------------------------------------
      # Subscription that the Network Manager is deployed in (owned by SLNM team)
      subscription: 84863f4a-6dec-4d3b-a75a-d52ac4e748b6
      # Configuration ID of ruleset that was created for SLNM.
      configId: /subscriptions/84863f4a-6dec-4d3b-a75a-d52ac4e748b6/resourceGroups/dfe3a810-861c-44da-9b00-71e57a865194.rg/providers/Microsoft.Network/networkManagers/slnm.dfe3a810-861c-44da-9b00-71e57a865194.pb.ame.pd/securityAdminConfigurations/20250428.302ae31d-54de-44c9-8188-8ebb1217f840
      # Resource group that the Network Manager is deployed in (owned by SLNM team)
      resourceGroup: dfe3a810-861c-44da-9b00-71e57a865194.rg
      # Name of the Network Manager that was created for SLNM.
      name: slnm.dfe3a810-861c-44da-9b00-71e57a865194.pb.ame.pd
