######################################################################
######################################################################
# User inputs.
######################################################################
######################################################################
sharedInput:
  # Used by both internal go code and required for templates.
  # # The following are variables used when generating resources and pipeline modules.
  # A directory on your computer where the shared resources and pipeline folders will be stored.
  destinationDirPrefix: ../../service_hub_validation_service
  ################################
  # Variables required that are shared by resource, pipeline, and service templates.
  requiredInputs:
    # The official display name of your product.
    productDisplayName: AKS Service Hub Validation
    # The official short name (only lowercase letters) of your product.
    productShortName: servicehubval
    # The back-filled subscription id used for ev2 test infra deployment in corporate tenant.
    backfilledTestSubscriptionId: 049e57e6-ff8e-4e8f-91bf-5830bf32d150
    # The service tree id of your service.
    serviceTreeId: dfe3a810-861c-44da-9b00-71e57a865194
    # The second level service tree node id of your service.
    # For example, if Ownership Hierarchy: Cloud + AI Platform -> Azure Core -> Azure Management and Platforms -> Containers (BBURNS) -> AKS Service Hub
    # The second level service tree node id is the id for Azure Core.
    secondLevelServiceTreeNodeId: ef733b4f-da1d-4909-8495-73785ce205aa
    # The principal id of your service admin security group for production resources.
    prodAdminSecurityGroupId: 72dfc0be-0b66-4998-afa2-8b9c4d26bf21
    # The principal Id of your service admin security group that exists in corp tenant. This will give access to the Kusto production cluster even in the corp tenant.
    corpAdminSecurityGroupId: adcc434d-5e83-4935-8d81-af89d05aad4c # CRG-apaksservice-dakt-ReadWrite-1uh4
    # The tenant Id of the account that owns the AIRS registration.
    # This is a required property if the AIRS registration being used is not CORP/MSFT account.
    airsRegisteredUserTenantId: 33e01921-4d64-4f8c-a055-5bdaffd5e33d
    # The AAD principal object Id of the owner of the AIRS registration.
    # This user is set as the Account Admin of the created subscriptions.
    # Refer to https://ev2docs.azure.net/features/service-artifacts/actions/subscriptionProvisioningParameters.html#airs-configuration
    # for how to create/get this value.
    airsRegisteredUserPrincipalId: 23551938-26fb-4713-bb60-456716564972
    # The primary email address for Ev2 rollout notifications. Use ; as separator for multiple emails
    contactEmail: chamakawa@microsoft.com;ksehgal@microsoft.com
    # The PC Code for the subscription billing.
    pcCode: P84536
    # The cost category for the subscription billing and to be one of the below listed values:
    # FX: Cost of Goods Sold
    # FG: General and Administrative
    # FR: Research and Development
    # FS: Sales and Marketing
    costCategory: FR

###################################
# Shared resources variables
###################################
resourceInput:
  # The template name to use for the shared resources folder.
  # Only used by internal templating code to determine which template to use.
  templateName: resourcesTemplate
  ################################
  # Variables required by both internal templating code and the templates.
  # The directory name after destination_dir_prefix. It holds the shared resources.
  directoryName: shared-resources
###################################
# Pipeline files variables.
###################################
pipelineInput:
  # The template name to use for the pipelines folder.
  # Only used by internal templating code to determine which template to use.
  templateName: pipelineTemplate
  ################################
  # Used by both internal go code and required for templates.
  # The directory name after destination_dir_prefix. It holds the pipeline files.
  directoryName: pipeline-files
  ################################
  # Variables required by the pipeline templates.
  requiredInputs:
    # The name of the branch used to perform official build and release operations.
    defaultBranch: master