apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: {{ .Release.Namespace }}
data:
  kubernetes.conf: {{ .Files.Get "fluentd/kubernetes.conf" | quote }}
  fluentd.conf: {{ .Files.Get "fluentd/fluentd.conf" | quote }}
