# These variables need to be defined with default values **prior to** the if block so that they are
# in scope later on when used.
# TODO: format the fluentd and kubernetes conf files so easier to modify when deployed to cluster
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: geneva-kvcert
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.cert.msi_client_id | quote }}
    keyvaultName: {{ .Values.cert.keyvaultName | quote }}
    # cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: {{ .Values.cert.genevaCertName | quote }}
          objectType: secret
          objectAlias: {{ .Values.cert.pemFileName }}
    tenantId: {{ .Values.cert.tenantId | quote }}
