// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "buf.build/gen/go/service-hub/loggable/protocolbuffers/go/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *HelloRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *HelloRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`        // The city name
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`      // The state name
	Zipcode       int32                  `protobuf:"varint,3,opt,name=zipcode,proto3" json:"zipcode,omitempty"` // The zip code
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`    // The street name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipcode() int32 {
	if x != nil {
		return x.Zipcode
	}
	return 0
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

type CreateResourceGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region         string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateResourceGroupRequest) Reset() {
	*x = CreateResourceGroupRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceGroupRequest) ProtoMessage() {}

func (x *CreateResourceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResourceGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResourceGroupRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateResourceGroupRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type ReadResourceGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadResourceGroupRequest) Reset() {
	*x = ReadResourceGroupRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceGroupRequest) ProtoMessage() {}

func (x *ReadResourceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceGroupRequest.ProtoReflect.Descriptor instead.
func (*ReadResourceGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResourceGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadResourceGroupRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type ReadResourceGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceGroup *ResourceGroup         `protobuf:"bytes,1,opt,name=resourceGroup,proto3" json:"resourceGroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResourceGroupResponse) Reset() {
	*x = ReadResourceGroupResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResourceGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceGroupResponse) ProtoMessage() {}

func (x *ReadResourceGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceGroupResponse.ProtoReflect.Descriptor instead.
func (*ReadResourceGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResourceGroupResponse) GetResourceGroup() *ResourceGroup {
	if x != nil {
		return x.ResourceGroup
	}
	return nil
}

type DeleteResourceGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResourceGroupRequest) Reset() {
	*x = DeleteResourceGroupRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceGroupRequest) ProtoMessage() {}

func (x *DeleteResourceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResourceGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteResourceGroupRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type UpdateResourceGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResourceGroupRequest) Reset() {
	*x = UpdateResourceGroupRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceGroupRequest) ProtoMessage() {}

func (x *UpdateResourceGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResourceGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResourceGroupRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateResourceGroupRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type UpdateResourceGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceGroup *ResourceGroup         `protobuf:"bytes,1,opt,name=resourceGroup,proto3" json:"resourceGroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceGroupResponse) Reset() {
	*x = UpdateResourceGroupResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceGroupResponse) ProtoMessage() {}

func (x *UpdateResourceGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateResourceGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateResourceGroupResponse) GetResourceGroup() *ResourceGroup {
	if x != nil {
		return x.ResourceGroup
	}
	return nil
}

type ListResourceGroupsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListResourceGroupsRequest) Reset() {
	*x = ListResourceGroupsRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceGroupsRequest) ProtoMessage() {}

func (x *ListResourceGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListResourceGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourceGroupsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type ListResourceGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RgList        []*ResourceGroup       `protobuf:"bytes,1,rep,name=rgList,proto3" json:"rgList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceGroupResponse) Reset() {
	*x = ListResourceGroupResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceGroupResponse) ProtoMessage() {}

func (x *ListResourceGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceGroupResponse.ProtoReflect.Descriptor instead.
func (*ListResourceGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListResourceGroupResponse) GetRgList() []*ResourceGroup {
	if x != nil {
		return x.RgList
	}
	return nil
}

type ResourceGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGroup) Reset() {
	*x = ResourceGroup{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroup) ProtoMessage() {}

func (x *ResourceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroup.ProtoReflect.Descriptor instead.
func (*ResourceGroup) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceGroup) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CreateStorageAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RgName         string                 `protobuf:"bytes,1,opt,name=rgName,proto3" json:"rgName,omitempty"`
	SaName         string                 `protobuf:"bytes,2,opt,name=saName,proto3" json:"saName,omitempty"`
	Region         string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,4,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateStorageAccountRequest) Reset() {
	*x = CreateStorageAccountRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStorageAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageAccountRequest) ProtoMessage() {}

func (x *CreateStorageAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateStorageAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *CreateStorageAccountRequest) GetRgName() string {
	if x != nil {
		return x.RgName
	}
	return ""
}

func (x *CreateStorageAccountRequest) GetSaName() string {
	if x != nil {
		return x.SaName
	}
	return ""
}

func (x *CreateStorageAccountRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateStorageAccountRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type CreateStorageAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStorageAccountResponse) Reset() {
	*x = CreateStorageAccountResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStorageAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStorageAccountResponse) ProtoMessage() {}

func (x *CreateStorageAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStorageAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateStorageAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *CreateStorageAccountResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadStorageAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RgName         string                 `protobuf:"bytes,1,opt,name=rgName,proto3" json:"rgName,omitempty"`
	SaName         string                 `protobuf:"bytes,2,opt,name=saName,proto3" json:"saName,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadStorageAccountRequest) Reset() {
	*x = ReadStorageAccountRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStorageAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStorageAccountRequest) ProtoMessage() {}

func (x *ReadStorageAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStorageAccountRequest.ProtoReflect.Descriptor instead.
func (*ReadStorageAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ReadStorageAccountRequest) GetRgName() string {
	if x != nil {
		return x.RgName
	}
	return ""
}

func (x *ReadStorageAccountRequest) GetSaName() string {
	if x != nil {
		return x.SaName
	}
	return ""
}

func (x *ReadStorageAccountRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type ReadStorageAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StorageAccount *StorageAccount        `protobuf:"bytes,1,opt,name=storageAccount,proto3" json:"storageAccount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadStorageAccountResponse) Reset() {
	*x = ReadStorageAccountResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStorageAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStorageAccountResponse) ProtoMessage() {}

func (x *ReadStorageAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStorageAccountResponse.ProtoReflect.Descriptor instead.
func (*ReadStorageAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *ReadStorageAccountResponse) GetStorageAccount() *StorageAccount {
	if x != nil {
		return x.StorageAccount
	}
	return nil
}

type DeleteStorageAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RgName         string                 `protobuf:"bytes,1,opt,name=rgName,proto3" json:"rgName,omitempty"`
	SaName         string                 `protobuf:"bytes,2,opt,name=saName,proto3" json:"saName,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,3,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteStorageAccountRequest) Reset() {
	*x = DeleteStorageAccountRequest{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageAccountRequest) ProtoMessage() {}

func (x *DeleteStorageAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteStorageAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteStorageAccountRequest) GetRgName() string {
	if x != nil {
		return x.RgName
	}
	return ""
}

func (x *DeleteStorageAccountRequest) GetSaName() string {
	if x != nil {
		return x.SaName
	}
	return ""
}

func (x *DeleteStorageAccountRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type UpdateStorageAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RgName         string                 `protobuf:"bytes,1,opt,name=rgName,proto3" json:"rgName,omitempty"`
	SaName         string                 `protobuf:"bytes,2,opt,name=saName,proto3" json:"saName,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SubscriptionId string                 `protobuf:"bytes,4,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStorageAccountRequest) Reset() {
	*x = UpdateStorageAccountRequest{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageAccountRequest) ProtoMessage() {}

func (x *UpdateStorageAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateStorageAccountRequest) GetRgName() string {
	if x != nil {
		return x.RgName
	}
	return ""
}

func (x *UpdateStorageAccountRequest) GetSaName() string {
	if x != nil {
		return x.SaName
	}
	return ""
}

func (x *UpdateStorageAccountRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateStorageAccountRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type UpdateStorageAccountResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StorageAccount *StorageAccount        `protobuf:"bytes,1,opt,name=storageAccount,proto3" json:"storageAccount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStorageAccountResponse) Reset() {
	*x = UpdateStorageAccountResponse{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageAccountResponse) ProtoMessage() {}

func (x *UpdateStorageAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateStorageAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStorageAccountResponse) GetStorageAccount() *StorageAccount {
	if x != nil {
		return x.StorageAccount
	}
	return nil
}

type ListStorageAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RgName         string                 `protobuf:"bytes,1,opt,name=rgName,proto3" json:"rgName,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStorageAccountRequest) Reset() {
	*x = ListStorageAccountRequest{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageAccountRequest) ProtoMessage() {}

func (x *ListStorageAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageAccountRequest.ProtoReflect.Descriptor instead.
func (*ListStorageAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *ListStorageAccountRequest) GetRgName() string {
	if x != nil {
		return x.RgName
	}
	return ""
}

func (x *ListStorageAccountRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type ListStorageAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaList        []*StorageAccount      `protobuf:"bytes,1,rep,name=saList,proto3" json:"saList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageAccountResponse) Reset() {
	*x = ListStorageAccountResponse{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageAccountResponse) ProtoMessage() {}

func (x *ListStorageAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageAccountResponse.ProtoReflect.Descriptor instead.
func (*ListStorageAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *ListStorageAccountResponse) GetSaList() []*StorageAccount {
	if x != nil {
		return x.SaList
	}
	return nil
}

type StorageAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageAccount) Reset() {
	*x = StorageAccount{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageAccount) ProtoMessage() {}

func (x *StorageAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageAccount.ProtoReflect.Descriptor instead.
func (*StorageAccount) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *StorageAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StorageAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageAccount) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// ********************ASYNC OPERATIONS********************
type StartLongRunningOperationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EntityId            string                 `protobuf:"bytes,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	EntityType          string                 `protobuf:"bytes,2,opt,name=entityType,proto3" json:"entityType,omitempty"`
	ExpirationTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expirationTimestamp,proto3" json:"expirationTimestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartLongRunningOperationRequest) Reset() {
	*x = StartLongRunningOperationRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLongRunningOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLongRunningOperationRequest) ProtoMessage() {}

func (x *StartLongRunningOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLongRunningOperationRequest.ProtoReflect.Descriptor instead.
func (*StartLongRunningOperationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *StartLongRunningOperationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *StartLongRunningOperationRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *StartLongRunningOperationRequest) GetExpirationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return nil
}

type StartLongRunningOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLongRunningOperationResponse) Reset() {
	*x = StartLongRunningOperationResponse{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLongRunningOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLongRunningOperationResponse) ProtoMessage() {}

func (x *StartLongRunningOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLongRunningOperationResponse.ProtoReflect.Descriptor instead.
func (*StartLongRunningOperationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *StartLongRunningOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entityType,proto3" json:"entityType,omitempty"`
	OperationId   string                 `protobuf:"bytes,3,opt,name=operationId,proto3" json:"operationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *CancelOperationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CancelOperationRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CancelOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bbuf/validate/validate.proto\x1a\x0fproto/log.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\fHelloRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x02R\x04name\x12 \n" +
	"\x03age\x18\x02 \x01(\x05B\x0e\xbaH\a\x1a\x05\x10\x96\x01(\x01\x88\xb5\x18\x00R\x03age\x12>\n" +
	"\x05email\x18\x03 \x01(\tB(\xbaH!r\x1f\x10\x012\x1b^[\\w.-]+@[\\w.-]+\\.[\\w]{2,}$\x88\xb5\x18\x00R\x05email\x12'\n" +
	"\aaddress\x18\x04 \x01(\v2\b.AddressH\x00R\aaddress\x88\x01\x01B\n" +
	"\n" +
	"\b_address\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x96\x01\n" +
	"\aAddress\x12\x1b\n" +
	"\x04city\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04city\x12!\n" +
	"\x05state\x18\x02 \x01(\tB\v\xbaH\x04r\x02\x10\x01\x88\xb5\x18\x00R\x05state\x12&\n" +
	"\azipcode\x18\x03 \x01(\x05B\f\xbaH\t\x1a\a\x10\x9f\x8d\x06(\x90NR\azipcode\x12#\n" +
	"\x06street\x18\x04 \x01(\tB\v\xbaH\x04r\x02\x10\x01\x88\xb5\x18\x00R\x06street\"p\n" +
	"\x1aCreateResourceGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12&\n" +
	"\x0esubscriptionId\x18\x03 \x01(\tR\x0esubscriptionId\"V\n" +
	"\x18ReadResourceGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0esubscriptionId\x18\x02 \x01(\tR\x0esubscriptionId\"Q\n" +
	"\x19ReadResourceGroupResponse\x124\n" +
	"\rresourceGroup\x18\x01 \x01(\v2\x0e.ResourceGroupR\rresourceGroup\"X\n" +
	"\x1aDeleteResourceGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0esubscriptionId\x18\x02 \x01(\tR\x0esubscriptionId\"\xcc\x01\n" +
	"\x1aUpdateResourceGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x04tags\x18\x02 \x03(\v2%.UpdateResourceGroupRequest.TagsEntryR\x04tags\x12&\n" +
	"\x0esubscriptionId\x18\x03 \x01(\tR\x0esubscriptionId\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x1bUpdateResourceGroupResponse\x124\n" +
	"\rresourceGroup\x18\x01 \x01(\v2\x0e.ResourceGroupR\rresourceGroup\"C\n" +
	"\x19ListResourceGroupsRequest\x12&\n" +
	"\x0esubscriptionId\x18\x01 \x01(\tR\x0esubscriptionId\"C\n" +
	"\x19ListResourceGroupResponse\x12&\n" +
	"\x06rgList\x18\x01 \x03(\v2\x0e.ResourceGroupR\x06rgList\"O\n" +
	"\rResourceGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"\x8d\x01\n" +
	"\x1bCreateStorageAccountRequest\x12\x16\n" +
	"\x06rgName\x18\x01 \x01(\tR\x06rgName\x12\x16\n" +
	"\x06saName\x18\x02 \x01(\tR\x06saName\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12&\n" +
	"\x0esubscriptionId\x18\x04 \x01(\tR\x0esubscriptionId\"2\n" +
	"\x1cCreateStorageAccountResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"s\n" +
	"\x19ReadStorageAccountRequest\x12\x16\n" +
	"\x06rgName\x18\x01 \x01(\tR\x06rgName\x12\x16\n" +
	"\x06saName\x18\x02 \x01(\tR\x06saName\x12&\n" +
	"\x0esubscriptionId\x18\x03 \x01(\tR\x0esubscriptionId\"U\n" +
	"\x1aReadStorageAccountResponse\x127\n" +
	"\x0estorageAccount\x18\x01 \x01(\v2\x0f.StorageAccountR\x0estorageAccount\"u\n" +
	"\x1bDeleteStorageAccountRequest\x12\x16\n" +
	"\x06rgName\x18\x01 \x01(\tR\x06rgName\x12\x16\n" +
	"\x06saName\x18\x02 \x01(\tR\x06saName\x12&\n" +
	"\x0esubscriptionId\x18\x03 \x01(\tR\x0esubscriptionId\"\xea\x01\n" +
	"\x1bUpdateStorageAccountRequest\x12\x16\n" +
	"\x06rgName\x18\x01 \x01(\tR\x06rgName\x12\x16\n" +
	"\x06saName\x18\x02 \x01(\tR\x06saName\x12:\n" +
	"\x04tags\x18\x03 \x03(\v2&.UpdateStorageAccountRequest.TagsEntryR\x04tags\x12&\n" +
	"\x0esubscriptionId\x18\x04 \x01(\tR\x0esubscriptionId\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x1cUpdateStorageAccountResponse\x127\n" +
	"\x0estorageAccount\x18\x01 \x01(\v2\x0f.StorageAccountR\x0estorageAccount\"[\n" +
	"\x19ListStorageAccountRequest\x12\x16\n" +
	"\x06rgName\x18\x01 \x01(\tR\x06rgName\x12&\n" +
	"\x0esubscriptionId\x18\x02 \x01(\tR\x0esubscriptionId\"E\n" +
	"\x1aListStorageAccountResponse\x12'\n" +
	"\x06saList\x18\x01 \x03(\v2\x0f.StorageAccountR\x06saList\"P\n" +
	"\x0eStorageAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"\xac\x01\n" +
	" StartLongRunningOperationRequest\x12\x1a\n" +
	"\bentityId\x18\x01 \x01(\tR\bentityId\x12\x1e\n" +
	"\n" +
	"entityType\x18\x02 \x01(\tR\n" +
	"entityType\x12L\n" +
	"\x13expirationTimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13expirationTimestamp\"E\n" +
	"!StartLongRunningOperationResponse\x12 \n" +
	"\voperationId\x18\x01 \x01(\tR\voperationId\"v\n" +
	"\x16CancelOperationRequest\x12\x1a\n" +
	"\bentityId\x18\x01 \x01(\tR\bentityId\x12\x1e\n" +
	"\n" +
	"entityType\x18\x02 \x01(\tR\n" +
	"entityType\x12 \n" +
	"\voperationId\x18\x03 \x01(\tR\voperationId2\xa2\x18\n" +
	"\tMyGreeter\x12~\n" +
	"\bSayHello\x12\r.HelloRequest\x1a\v.HelloReply\"V\x92A?\x12\x0fSend a greeting\x1a,This operation sends a greeting to the user.\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/hello\x12\xd7\x01\n" +
	"\x13CreateResourceGroup\x12\x1b.CreateResourceGroupRequest\x1a\x16.google.protobuf.Empty\"\x8a\x01\x92AG\x12\x17Create a resource group\x1a,This operation creates a new resource group.\x82\xd3\xe4\x93\x02::\x01*\"5/subscriptions/{subscriptionId}/resourceGroups/{name}\x12\xdb\x01\n" +
	"\x11ReadResourceGroup\x12\x19.ReadResourceGroupRequest\x1a\x1a.ReadResourceGroupResponse\"\x8e\x01\x92AN\x12\x15Read a resource group\x1a5This operation reads the details of a resource group.\x82\xd3\xe4\x93\x027\x125/subscriptions/{subscriptionId}/resourceGroups/{name}\x12\xd0\x01\n" +
	"\x13DeleteResourceGroup\x12\x1b.DeleteResourceGroupRequest\x1a\x16.google.protobuf.Empty\"\x83\x01\x92AC\x12\x17Delete a resource group\x1a(This operation deletes a resource group.\x82\xd3\xe4\x93\x027*5/subscriptions/{subscriptionId}/resourceGroups/{name}\x12\xe8\x01\n" +
	"\x13UpdateResourceGroup\x12\x1b.UpdateResourceGroupRequest\x1a\x1c.UpdateResourceGroupResponse\"\x95\x01\x92AO\x12\x17Update a resource group\x1a4This operation updates the tags of a resource group.\x82\xd3\xe4\x93\x02=:\x04tags\x1a5/subscriptions/{subscriptionId}/resourceGroups/{name}\x12\xd1\x01\n" +
	"\x12ListResourceGroups\x12\x1a.ListResourceGroupsRequest\x1a\x1a.ListResourceGroupResponse\"\x82\x01\x92AI\x12\x18List all resource groups\x1a-This operation lists all the resource groups.\x82\xd3\xe4\x93\x020\x12./subscriptions/{subscriptionId}/resourceGroups\x12\x99\x02\n" +
	"\x14CreateStorageAccount\x12\x1c.CreateStorageAccountRequest\x1a\x1d.CreateStorageAccountResponse\"\xc3\x01\x92AI\x12\x18Create a storage account\x1a-This operation creates a new storage account.\x82\xd3\xe4\x93\x02q:\x01*\"l/subscriptions/{subscriptionId}/resourceGroups/{rgName}/providers/Microsoft.Storage/storageAccounts/{saName}\x12\x97\x02\n" +
	"\x12ReadStorageAccount\x12\x1a.ReadStorageAccountRequest\x1a\x1b.ReadStorageAccountResponse\"\xc7\x01\x92AP\x12\x16Read a storage account\x1a6This operation reads the details of a storage account.\x82\xd3\xe4\x93\x02n\x12l/subscriptions/{subscriptionId}/resourceGroups/{rgName}/providers/Microsoft.Storage/storageAccounts/{saName}\x12\x8b\x02\n" +
	"\x14DeleteStorageAccount\x12\x1c.DeleteStorageAccountRequest\x1a\x16.google.protobuf.Empty\"\xbc\x01\x92AE\x12\x18Delete a storage account\x1a)This operation deletes a storage account.\x82\xd3\xe4\x93\x02n*l/subscriptions/{subscriptionId}/resourceGroups/{rgName}/providers/Microsoft.Storage/storageAccounts/{saName}\x12\xa4\x02\n" +
	"\x14UpdateStorageAccount\x12\x1c.UpdateStorageAccountRequest\x1a\x1d.UpdateStorageAccountResponse\"\xce\x01\x92AQ\x12\x18Update a storage account\x1a5This operation updates the tags of a storage account.\x82\xd3\xe4\x93\x02t:\x04tags\x1al/subscriptions/{subscriptionId}/resourceGroups/{rgName}/providers/Microsoft.Storage/storageAccounts/{saName}\x12\x8a\x02\n" +
	"\x13ListStorageAccounts\x12\x1a.ListStorageAccountRequest\x1a\x1b.ListStorageAccountResponse\"\xb9\x01\x92AK\x12\x19List all storage accounts\x1a.This operation lists all the storage accounts.\x82\xd3\xe4\x93\x02e\x12c/subscriptions/{subscriptionId}/resourceGroups/{rgName}/providers/Microsoft.Storage/storageAccounts\x12\xe5\x01\n" +
	"\x19StartLongRunningOperation\x12!.StartLongRunningOperationRequest\x1a\".StartLongRunningOperationResponse\"\x80\x01\x92AT\x12\x1fStart a long running operation.\x1a1This call starts an async long running operation.\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/async/longrunningoperation\x12\xea\x01\n" +
	"\x0fCancelOperation\x12\x17.CancelOperationRequest\x1a\x16.google.protobuf.Empty\"\xa5\x01\x92AV\x12\x1aCancel an async operation.\x1a8This operation will set an async operation to cancelled.\x82\xd3\xe4\x93\x02F:\x01*\"A/v1/entity/{entityType}/{entityId}/operation/{operationId}/cancelB}B\bApiProtoP\x01Zodev.azure.com/service-hub-flg/service_hub_validation/_git/service_hub_validation_service.git/mygreeterv3/api/v1b\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_proto_goTypes = []any{
	(*HelloRequest)(nil),                      // 0: HelloRequest
	(*HelloReply)(nil),                        // 1: HelloReply
	(*Address)(nil),                           // 2: Address
	(*CreateResourceGroupRequest)(nil),        // 3: CreateResourceGroupRequest
	(*ReadResourceGroupRequest)(nil),          // 4: ReadResourceGroupRequest
	(*ReadResourceGroupResponse)(nil),         // 5: ReadResourceGroupResponse
	(*DeleteResourceGroupRequest)(nil),        // 6: DeleteResourceGroupRequest
	(*UpdateResourceGroupRequest)(nil),        // 7: UpdateResourceGroupRequest
	(*UpdateResourceGroupResponse)(nil),       // 8: UpdateResourceGroupResponse
	(*ListResourceGroupsRequest)(nil),         // 9: ListResourceGroupsRequest
	(*ListResourceGroupResponse)(nil),         // 10: ListResourceGroupResponse
	(*ResourceGroup)(nil),                     // 11: ResourceGroup
	(*CreateStorageAccountRequest)(nil),       // 12: CreateStorageAccountRequest
	(*CreateStorageAccountResponse)(nil),      // 13: CreateStorageAccountResponse
	(*ReadStorageAccountRequest)(nil),         // 14: ReadStorageAccountRequest
	(*ReadStorageAccountResponse)(nil),        // 15: ReadStorageAccountResponse
	(*DeleteStorageAccountRequest)(nil),       // 16: DeleteStorageAccountRequest
	(*UpdateStorageAccountRequest)(nil),       // 17: UpdateStorageAccountRequest
	(*UpdateStorageAccountResponse)(nil),      // 18: UpdateStorageAccountResponse
	(*ListStorageAccountRequest)(nil),         // 19: ListStorageAccountRequest
	(*ListStorageAccountResponse)(nil),        // 20: ListStorageAccountResponse
	(*StorageAccount)(nil),                    // 21: StorageAccount
	(*StartLongRunningOperationRequest)(nil),  // 22: StartLongRunningOperationRequest
	(*StartLongRunningOperationResponse)(nil), // 23: StartLongRunningOperationResponse
	(*CancelOperationRequest)(nil),            // 24: CancelOperationRequest
	nil,                                       // 25: UpdateResourceGroupRequest.TagsEntry
	nil,                                       // 26: UpdateStorageAccountRequest.TagsEntry
	(*timestamppb.Timestamp)(nil),             // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 28: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	2,  // 0: HelloRequest.address:type_name -> Address
	11, // 1: ReadResourceGroupResponse.resourceGroup:type_name -> ResourceGroup
	25, // 2: UpdateResourceGroupRequest.tags:type_name -> UpdateResourceGroupRequest.TagsEntry
	11, // 3: UpdateResourceGroupResponse.resourceGroup:type_name -> ResourceGroup
	11, // 4: ListResourceGroupResponse.rgList:type_name -> ResourceGroup
	21, // 5: ReadStorageAccountResponse.storageAccount:type_name -> StorageAccount
	26, // 6: UpdateStorageAccountRequest.tags:type_name -> UpdateStorageAccountRequest.TagsEntry
	21, // 7: UpdateStorageAccountResponse.storageAccount:type_name -> StorageAccount
	21, // 8: ListStorageAccountResponse.saList:type_name -> StorageAccount
	27, // 9: StartLongRunningOperationRequest.expirationTimestamp:type_name -> google.protobuf.Timestamp
	0,  // 10: MyGreeter.SayHello:input_type -> HelloRequest
	3,  // 11: MyGreeter.CreateResourceGroup:input_type -> CreateResourceGroupRequest
	4,  // 12: MyGreeter.ReadResourceGroup:input_type -> ReadResourceGroupRequest
	6,  // 13: MyGreeter.DeleteResourceGroup:input_type -> DeleteResourceGroupRequest
	7,  // 14: MyGreeter.UpdateResourceGroup:input_type -> UpdateResourceGroupRequest
	9,  // 15: MyGreeter.ListResourceGroups:input_type -> ListResourceGroupsRequest
	12, // 16: MyGreeter.CreateStorageAccount:input_type -> CreateStorageAccountRequest
	14, // 17: MyGreeter.ReadStorageAccount:input_type -> ReadStorageAccountRequest
	16, // 18: MyGreeter.DeleteStorageAccount:input_type -> DeleteStorageAccountRequest
	17, // 19: MyGreeter.UpdateStorageAccount:input_type -> UpdateStorageAccountRequest
	19, // 20: MyGreeter.ListStorageAccounts:input_type -> ListStorageAccountRequest
	22, // 21: MyGreeter.StartLongRunningOperation:input_type -> StartLongRunningOperationRequest
	24, // 22: MyGreeter.CancelOperation:input_type -> CancelOperationRequest
	1,  // 23: MyGreeter.SayHello:output_type -> HelloReply
	28, // 24: MyGreeter.CreateResourceGroup:output_type -> google.protobuf.Empty
	5,  // 25: MyGreeter.ReadResourceGroup:output_type -> ReadResourceGroupResponse
	28, // 26: MyGreeter.DeleteResourceGroup:output_type -> google.protobuf.Empty
	8,  // 27: MyGreeter.UpdateResourceGroup:output_type -> UpdateResourceGroupResponse
	10, // 28: MyGreeter.ListResourceGroups:output_type -> ListResourceGroupResponse
	13, // 29: MyGreeter.CreateStorageAccount:output_type -> CreateStorageAccountResponse
	15, // 30: MyGreeter.ReadStorageAccount:output_type -> ReadStorageAccountResponse
	28, // 31: MyGreeter.DeleteStorageAccount:output_type -> google.protobuf.Empty
	18, // 32: MyGreeter.UpdateStorageAccount:output_type -> UpdateStorageAccountResponse
	20, // 33: MyGreeter.ListStorageAccounts:output_type -> ListStorageAccountResponse
	23, // 34: MyGreeter.StartLongRunningOperation:output_type -> StartLongRunningOperationResponse
	28, // 35: MyGreeter.CancelOperation:output_type -> google.protobuf.Empty
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
