# Run a Bash script on macOS, Linux, or Windows
jobs:
  - job: operationcontainerTestCoverage
    displayName: "[operationcontainer] Generate test coverage reports"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: Bash@3
        displayName: Test Suite Check
        inputs:
          targetType: "filePath"
          filePath: operationcontainer/server/test/testSuites.sh
          failOnStderr: false
          workingDirectory: $(WORKING_DIRECTORY)
      - task: Bash@3
        displayName: Test Coverage for Output
        inputs:
          targetType: "filePath"
          filePath: operationcontainer/server/test/testCoverageOutput.sh
          failOnStderr: false
          workingDirectory: $(WORKING_DIRECTORY)
        env:
          threshold: 5
          READPAT: $(READPAT)
      - task: PublishPipelineArtifact@1
        displayName: "Publish test coverage as an artifact"
        inputs:
          targetPath: "$(WORKING_DIRECTORY)operationcontainer/server/test/coverage_reports"
          artifactName: operationcontainer_CoverageReports
  - job: operationcontainerBuildImage
    displayName: "[operationcontainer] Build image"
    pool:
      vmImage: "ubuntu-latest"
    dependsOn:
      #This job is mentioned in main pipeline yaml file (within pipeline files directory)
      - GenerateAndPublishEnvConfig
    steps:
      - template: ../pipeline-files/downloadRequirements.yaml
      #TODO: Change this to split build and push, when build option is available instead of buildx.
      - task: Bash@3
        displayName: Build image
        inputs:
          targetType: "filePath"
          filePath: operationcontainer/server/test/buildImage.sh
          failOnStderr: false
          workingDirectory: $(WORKING_DIRECTORY)
        env:
          WORKSPACE: false
          READPAT: $(READPAT)
      - task: PublishPipelineArtifact@1
        displayName: "Publish docker image as an artifact"
        inputs:
          targetPath: "$(WORKING_DIRECTORY)operationcontainer/server/generated/operationcontainer-image.tar"
          artifactName: operationcontainer-image
  - job: operationcontainerPushImage
    displayName: "[operationcontainer] Push image"
    pool:
      vmImage: "ubuntu-latest"
    dependsOn:
      #This job is mentioned in main pipeline yaml file (within pipeline files directory)
      - ProvisionSharedResources
      - operationcontainerBuildImage
    steps:
      - template: ../pipeline-files/downloadRequirements.yaml
      - task: DownloadPipelineArtifact@2
        displayName: "Download docker image artifact"
        inputs:
          artifactName: operationcontainer-image
          targetPath: "$(System.DefaultWorkingDirectory)/$(WORKING_DIRECTORY)operationcontainer/server/generated/"
      - task: AzureCLI@2
        displayName: Push image
        inputs:
          # azureSubscription corresponds to the name of the azure resource manager service
          # connection that is supposed to be used for the pipeline task.
          azureSubscription: ServiceHubValidation_ServiceConnection
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: operationcontainer/server/test/pushImage.sh
          workingDirectory: $(WORKING_DIRECTORY)
  - job: operationcontainerProvisionServiceResources
    displayName: "[operationcontainer] Provision service specific resources"
    pool:
      vmImage: "ubuntu-latest"
    dependsOn:
      #This job is mentioned in main pipeline yaml file (within pipeline files directory)
      - ProvisionSharedResources
    steps:
      - template: ../pipeline-files/downloadRequirements.yaml
      - task: AzureCLI@2
        displayName: Provision service specific resources
        inputs:
          # azureSubscription corresponds to the name of the azure resource manager service
          # connection that is supposed to be used for the pipeline task.
          azureSubscription: ServiceHubValidation_ServiceConnection
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: operationcontainer/server/test/provisionServiceResources.sh
          workingDirectory: $(WORKING_DIRECTORY)
          # If we re-add make service into deploy-resources, these arguments will 
          # be needed for pipeline to successfully access the private repository.
          # arguments: $(READPAT)
      - task: PublishPipelineArtifact@1
        displayName: "Publish artifact directory"
        inputs:
          targetPath: "$(WORKING_DIRECTORY)operationcontainer/server/artifacts"
          artifactName: operationcontainer_ArtifactDirectory
      - task: PublishPipelineArtifact@1
        displayName: "Publish adx dashboard as an artifact"
        inputs:
          targetPath: "$(WORKING_DIRECTORY)operationcontainer/server/monitoring/dashboard/adx-dashboard.json"
          artifactName: operationcontainer-dashboard
      - task: Bash@3
        displayName: Prepare all markdown files to publish
        inputs:
          targetType: "inline"
          script: |
            cd operationcontainer/server
            mkdir markdown_files
            if ls resources/**/*.md 1> /dev/null 2>&1; then
              find resources -name "*.md" -not -name "ai-summary.md" -exec mv {} markdown_files \;
            fi
          failOnStderr: false
          workingDirectory: $(WORKING_DIRECTORY)
      - task: PublishPipelineArtifact@1
        displayName: "Publish service specific resource markdown files"
        inputs:
          targetPath: "$(WORKING_DIRECTORY)operationcontainer/server/markdown_files"
          artifactName: operationcontainer_SpecificResourceMarkdownFiles
  - job: operationcontainerDeployService
    displayName: "[operationcontainer] Deploy Service"
    pool:
      vmImage: "ubuntu-latest"
    dependsOn:
      - operationcontainerPushImage
      - operationcontainerProvisionServiceResources
    steps:
      - template: ../pipeline-files/downloadRequirements.yaml
      - task: DownloadPipelineArtifact@2
        displayName: "Download artifact directory"
        inputs:
          artifactName: operationcontainer_ArtifactDirectory
          targetPath: "$(System.DefaultWorkingDirectory)/$(WORKING_DIRECTORY)operationcontainer/server/artifacts"
      - task: AzureCLI@2
        displayName: Deploy and test service
        inputs:
          # azureSubscription corresponds to the name of the azure resource manager service
          # connection that is supposed to be used for the pipeline task.
          azureSubscription: ServiceHubValidation_ServiceConnection
          scriptType: "bash"
          scriptLocation: "scriptPath"
          scriptPath: operationcontainer/server/test/deployService.sh
          workingDirectory: $(WORKING_DIRECTORY)
